// app/legal/terms/page.tsx
export const metadata = { title: "Terms of Service — Ellie" };

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 px-6 md:px-10 py-10">
      <div className="max-w-3xl mx-auto text-white">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="mt-2 text-sm text-white/60">Last updated: December 4, 2025</p>

        <section className="mt-6 space-y-6 text-white/90 leading-7">
          <p>
            Welcome to Ellie. By accessing or using our service, you agree to be bound by these Terms of Service.
            If you do not agree to these terms, please do not use our service.
          </p>

          <div className="bg-purple-500/10 border border-purple-500/30 rounded-lg p-4">
            <h2 className="text-xl font-semibold text-purple-300">Age Requirement</h2>
            <p className="mt-2">
              <strong>You must be at least 18 years old to use Ellie.</strong> By creating an account or using our service,
              you represent and warrant that you are at least 18 years of age. If you are under 18, you are prohibited
              from using this service. We reserve the right to terminate accounts of users who misrepresent their age.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Description of Service</h2>
            <p className="mt-2">
              Ellie is an AI-powered interactive entertainment platform that provides text-based roleplay conversations
              and AI-generated digital content. The service is designed for mature audiences and supports unrestricted,
              open-ended creative interactions.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">AI-Generated Content Disclaimer</h2>
            <p className="mt-2">
              Ellie is an artificial intelligence chatbot. All characters, images, visuals, and scenarios are entirely
              fictional and generated by computer software. <strong>No actual human beings are depicted in any content.</strong> All
              characters appearing in this content are fictitious and represented as 18 years of age or older.
              This service is for entertainment purposes only.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Account Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              <li>You are responsible for all activity that occurs under your account</li>
              <li>You agree to notify us immediately of any unauthorized use of your account</li>
              <li>You may not share, sell, or transfer your account to another person</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Subscriptions & Payments</h2>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Paid subscriptions automatically renew until canceled</li>
              <li>You may cancel your subscription at any time through your account settings</li>
              <li>Cancellation takes effect at the end of your current billing period</li>
              <li>Prices and features are subject to change with notice</li>
              <li>All payments are processed securely by our third-party payment processor</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Refund Policy</h2>
            <p className="mt-2">
              Due to the nature of digital services, all sales are generally final. Refund requests are handled on a
              case-by-case basis at our sole discretion. If you believe you are entitled to a refund due to technical
              issues or billing errors, please contact us at support@ellie-elite.com within 7 days of the charge.
              We reserve the right to deny refund requests for services that have been substantially used.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Acceptable Use</h2>
            <p className="mt-2">You agree NOT to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Use the service for any unlawful purpose</li>
              <li>Attempt to reverse engineer, decompile, or extract source code from our service</li>
              <li>Interfere with or disrupt the service or servers</li>
              <li>Share content from the service that violates any third-party rights</li>
              <li>Use automated systems or bots to access the service</li>
              <li>Attempt to bypass any security measures or access restrictions</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Content & Intellectual Property</h2>
            <p className="mt-2">
              You retain ownership of any content you submit to the service. By using Ellie, you grant us a limited
              license to process your inputs to provide responses. All AI-generated content, the Ellie character,
              branding, and service design are our intellectual property. You may not reproduce, distribute, or
              create derivative works from our content without permission.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Disclaimer of Warranties</h2>
            <p className="mt-2">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
              AND NON-INFRINGEMENT. We do not warrant that the service will be uninterrupted, secure, or error-free.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Limitation of Liability</h2>
            <p className="mt-2">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
              CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR
              INDIRECTLY. Our total liability for any claim arising from the service shall not exceed the amount
              you paid us in the 12 months preceding the claim.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Termination</h2>
            <p className="mt-2">
              We may suspend or terminate your access to the service at any time, with or without cause, and with or
              without notice. Upon termination, your right to use the service will immediately cease. Provisions that
              by their nature should survive termination will survive (including limitations of liability and
              intellectual property provisions).
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Changes to Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. We will notify you of material changes by posting the new
              terms on this page and updating the &quot;Last updated&quot; date. Your continued use of the service after
              changes constitutes acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Governing Law</h2>
            <p className="mt-2">
              These Terms shall be governed by and construed in accordance with applicable law, without regard to
              conflict of law principles.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-purple-300">Contact Us</h2>
            <p className="mt-2">
              If you have questions about these Terms, contact us at:{" "}
              <a className="underline text-purple-400 hover:text-purple-300" href="mailto:support@ellie-elite.com">
                support@ellie-elite.com
              </a>
            </p>
          </div>
        </section>
      </div>
    </main>
  );
}
